#后台管理服务配置
[admin]
#后台服务绑定地址和端口
address = ":8080"
#websocket IP,为空时，自动识别内网IP
websocketIp = ""
#后台服务静态资源目录
serverRoot = "public"
#登陆页面展示名称
businessName = "在上邻里"
companyName = "四川在上科技有限公司"

# 数据库配置
[database]
#主数据库
master = "root:123456@tcp(127.0.0.1:3306)/zskj_api?charset=utf8mb4&parseTime=true&loc=Local"
#从数据库 如果为空则表示只使用主数据
slave = ""

# Redis配置
[redis]
# 使用redis存session
status = true
# 连接信息
host = "127.0.0.1:6379"
password = "123456"
