// Code generated by protoc-gen-go. DO NOT EDIT.
// source: printer_provider.proto

package printer_provider

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 参数定义
type RequestParam struct {
	PrinterName          string   `protobuf:"bytes,1,opt,name=printerName,proto3" json:"printerName,omitempty"`
	DpfPath              string   `protobuf:"bytes,2,opt,name=dpfPath,proto3" json:"dpfPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestParam) Reset()         { *m = RequestParam{} }
func (m *RequestParam) String() string { return proto.CompactTextString(m) }
func (*RequestParam) ProtoMessage()    {}
func (*RequestParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_2adf6509b244fc45, []int{0}
}

func (m *RequestParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestParam.Unmarshal(m, b)
}
func (m *RequestParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestParam.Marshal(b, m, deterministic)
}
func (m *RequestParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestParam.Merge(m, src)
}
func (m *RequestParam) XXX_Size() int {
	return xxx_messageInfo_RequestParam.Size(m)
}
func (m *RequestParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestParam.DiscardUnknown(m)
}

var xxx_messageInfo_RequestParam proto.InternalMessageInfo

func (m *RequestParam) GetPrinterName() string {
	if m != nil {
		return m.PrinterName
	}
	return ""
}

func (m *RequestParam) GetDpfPath() string {
	if m != nil {
		return m.DpfPath
	}
	return ""
}

// 返回信息定义
type Message struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2adf6509b244fc45, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Message) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestParam)(nil), "RequestParam")
	proto.RegisterType((*Message)(nil), "Message")
}

func init() {
	proto.RegisterFile("printer_provider.proto", fileDescriptor_2adf6509b244fc45)
}

var fileDescriptor_2adf6509b244fc45 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3f, 0x4b, 0xc5, 0x30,
	0x14, 0xc5, 0xad, 0x15, 0xab, 0x57, 0x85, 0x92, 0x41, 0x42, 0xa7, 0x52, 0x1c, 0x9c, 0x22, 0xe8,
	0xe2, 0x2c, 0x4e, 0x82, 0x12, 0xfa, 0x05, 0x24, 0x26, 0x37, 0xb1, 0x43, 0x9b, 0x78, 0x13, 0xfb,
	0xf9, 0x1f, 0xcd, 0xcb, 0x83, 0x6e, 0xe7, 0xfe, 0x39, 0x87, 0xdf, 0x81, 0xfb, 0x40, 0xd3, 0x92,
	0x90, 0xbe, 0x03, 0xf9, 0x75, 0x32, 0x48, 0x22, 0x90, 0x4f, 0x7e, 0xf8, 0x80, 0xdb, 0x11, 0xff,
	0xfe, 0x31, 0x26, 0xa9, 0x48, 0xcd, 0xac, 0x87, 0x9b, 0xf2, 0xf9, 0xa5, 0x66, 0xe4, 0x55, 0x5f,
	0x3d, 0x5e, 0x8f, 0xfb, 0x15, 0xe3, 0xd0, 0x98, 0x60, 0xa5, 0x4a, 0xbf, 0xfc, 0x3c, 0x5f, 0x4f,
	0xe3, 0xf0, 0x04, 0xcd, 0x27, 0xc6, 0xa8, 0x1c, 0x32, 0x06, 0x17, 0xda, 0x9b, 0xa3, 0xbf, 0x1e,
	0xb3, 0x66, 0x2d, 0xd4, 0x73, 0x74, 0xc5, 0xb4, 0xc9, 0xe7, 0x57, 0x68, 0xdf, 0x8d, 0x95, 0x5b,
	0xb8, 0x2c, 0x58, 0xec, 0x01, 0x1a, 0xe7, 0x65, 0x92, 0xc6, 0xb2, 0x3b, 0xb1, 0x47, 0xeb, 0xae,
	0x44, 0x49, 0x1f, 0xce, 0xde, 0x3a, 0xe0, 0x7a, 0x11, 0x8e, 0x82, 0x16, 0x11, 0x69, 0x9d, 0x34,
	0x8a, 0x60, 0x6c, 0xc6, 0xfc, 0xb9, 0xcc, 0xcd, 0x5e, 0x0e, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb5,
	0xf0, 0xd2, 0x42, 0xf3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DdfPrintProviderClient is the client API for DdfPrintProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DdfPrintProviderClient interface {
	GoPtPdf(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*Message, error)
}

type ddfPrintProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewDdfPrintProviderClient(cc grpc.ClientConnInterface) DdfPrintProviderClient {
	return &ddfPrintProviderClient{cc}
}

func (c *ddfPrintProviderClient) GoPtPdf(ctx context.Context, in *RequestParam, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/DdfPrintProvider/goPtPdf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DdfPrintProviderServer is the server API for DdfPrintProvider service.
type DdfPrintProviderServer interface {
	GoPtPdf(context.Context, *RequestParam) (*Message, error)
}

// UnimplementedDdfPrintProviderServer can be embedded to have forward compatible implementations.
type UnimplementedDdfPrintProviderServer struct {
}

func (*UnimplementedDdfPrintProviderServer) GoPtPdf(ctx context.Context, req *RequestParam) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoPtPdf not implemented")
}

func RegisterDdfPrintProviderServer(s *grpc.Server, srv DdfPrintProviderServer) {
	s.RegisterService(&_DdfPrintProvider_serviceDesc, srv)
}

func _DdfPrintProvider_GoPtPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdfPrintProviderServer).GoPtPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DdfPrintProvider/GoPtPdf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdfPrintProviderServer).GoPtPdf(ctx, req.(*RequestParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _DdfPrintProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DdfPrintProvider",
	HandlerType: (*DdfPrintProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "goPtPdf",
			Handler:    _DdfPrintProvider_GoPtPdf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "printer_provider.proto",
}
